# Generated by Django 5.0.2 on 2024-02-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_prettynum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prettynum", old_name="level_choices", new_name="level",
        ),
    ]
